### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by schneiderkh** [jishi/node-sonos-web-controller#17]
Hallo from Germany,
with the new SONOS-Version the old iPad1 and iPod touch will not work any more.
So i am look for a web-controller and find you. I use SONOS as "alarm clock" and my NAS
was not fast enough, and SONOS start the buzzer :-(
So I take a Raspi with and old 60GB SSD USB Drive and I have a 5Watt fast NAS for SONOS.
In the old NAS Sonos spin up all drives to get a new MP3 - not good.
The Question about a NAS for SONOS come on and on in the German SONOS forum.

On this SONOS-NAS I install your Web-Controller and it work very good :-)

I think it is a good way to put NAS and Web-Controller together.
Many people are looking for a cheap SONOS controller!
I will buy now a "cubietruck" to get a faster Raspi with IR-Port, good case an a SATA-Port.
So I hope to use a IP-Remote to control SONOS :-)

Can we work together ?

How can I use the "dashboard mode" ?

**Comment by jishi** [comment]
Considered abandoned
