### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by mraeymaekers** [jishi/node-sonos-web-controller#23]
There is nowhere on Github I can submit my SINCERE congratulations for this idea. I installed it on my Pi and it works like a charm. Granted, it is an alpha, but the idea is definitely there!
Continue the good work.

Kind regards

**Comment by jishi** [comment]
Thank you very much, appreciate the feedback. Unfortunately I haven't had much time lately to work on it, but I still have a a few ideas that I want to implement, so it isn't dead.
