### ISSUE TITLE
Song duration stuck at 1:58

### ISSUE THREAD

**Issue by jasperla** [jishi/node-sonos-web-controller#25]
For every song that I play the duration is set to 2:00 and after one or two seconds the progress stops. This happens with firefox, chrome and safari.

![Duration stuck at 1:58](http://jasper.la/dump/158.png)

**Comment by jasperla** [comment]
Actually, it's stuck at `-1:58`. When looking at `updateTransportState()` the duration is correctly set but it seems the GUI doesn't get the event to update the progressbar?

**Comment by jishi** [comment]
I have fixed this now, it broke because of a pull request that was supposed to fix radio information. pull the latest version and run npm install which would probably update sonos-discovery to 0.15.3, otherwise remove the node_modules folder and run npm install again.

**Comment by jasperla** [comment]
Thanks, but could you please tag 0.15.3 too then?

**Comment by jishi** [comment]
Gah, forgot that it doesn't push tags with a regular push. Fixed now, sorry about that.

**Comment by Explorer-OL** [comment]
Hi Jishi,

It seems that this issue of songs are continuing to play. Play button sticks without the possibility to get to pause.
Running windows 10 with Chrome version 76.0.3809.100.
Node version 8.11.3
Thx
OL
