### ISSUE TITLE
Web-Controller with Firefox - Volume Level stays at 100%

### ISSUE THREAD

**Issue by looxer01** [jishi/node-sonos-web-controller#29]
Hi,
When I use the Webcontroller latest version   "version": "0.12.3" with firefox and if I try to adjust the volume it immediately goes to 100%. Then can not adjust the volume anymore.
All works fine with Chrome though.

**Comment by jishi** [comment]
Could you please provide Firefox version, platform (windows, OS X, Linux) and whether this affects the group volume and/or individual volume? It would be a time saver for me, thank you.

**Comment by looxer01** [comment]
sorry for not detailed enough 
I am using windows 8.1, Firefox version is 36.0.4
I have tried in single volume mode and group volume. 
It happens in both cases. I am adding a screen print as it is even visible

thats what I am doing:
- switching on a radio channel
- trying to take the volume to the right or left
- then the volume sign actually goes to the very right as you can see in the attached
nevertheless the volume turns to the highest level
In group the same happens for both cases: level of speaker but also if I try on individual speaker in group mode

I hope this is better now :)

**Comment by jishi** [comment]
You seem to be running this in iobroker. I need you to check if this is reproducible outside of iobroker (if you visit the web controller directly). I can't seem to reproduce it here using Firefox in win 7. 

If it is broken in iobroker, I need to be able to reproduce a similar environment. The rendering seems to be broken as well, so I'm not sure how it actually embeds the controller on that page. Maybe @GermanBluefox could assist with some insights?

**Comment by looxer01** [comment]
yes - you are right - it is iobroker and I checked it without it meanwhile.
That it seems to be ok. So it might be related with the Iframe in iobroker / dashui
I have left a note in the iobroker forum - not sure how this can be fixed then

**Comment by jishi** [comment]
Well, since you claim it works in Chrome, it's probably just some tiny detail that breaks when in an iframe. If you could provide me with a minimal iframe setup that suffers from the same issue (without iobroker) I'll see what I can do.

**Comment by GermanBluefox** [comment]
I cannot reproduce this too. We are trying now to make the error circle smaller.

**Comment by looxer01** [comment]
it is now fixed in ioBroker. The issue is actually coming from DashUI and I importet the view from there.
The Webinterface is now working ok in ioBroker. Thank you very much to both of you.
