### ISSUE TITLE
Volume Slider for Touch Devices

### ISSUE THREAD

**Issue by Wolbolar** [jishi/node-sonos-web-controller#32]
It would be great if the volume slider would also work on touch devices, at the moment it can only be used with a mouse.

**Comment by jishi** [comment]
I have been working on a mobile version that will have a touch slider instead. I have no plans on implementing this on the desktop-version since it is badly designed for those screen sizes anyway. Unless you are planning on using it on a touch-based laptop, this should suffice?

**Comment by Wolbolar** [comment]
I´m planning to use the web controller as a part of home automation remote web site. So a mobile version would be enough. The only important thing it has to work on touch device, layout or design is not so much of importance.

**Comment by jishi** [comment]
There is a semi-working version at /m now. Please try it out and let me know your result.
