### ISSUE TITLE
Unnamed room

### ISSUE THREAD

**Issue by odcinek** [jishi/node-sonos-web-controller#33]
Stereo pair of Play:1s shows up as "Unnamed room".
![screenshot from 2015-06-03 20 51 27](https://cloud.githubusercontent.com/assets/217108/7976662/e4e5015c-0a32-11e5-8595-a2513d0f1f74.png)

**Comment by odcinek** [comment]
It went away after a restart of the web-controller.

**Comment by jishi** [comment]
Yeah, this is a known error. It will break if you remove or add new players to your system. This issue belongs on node-sonos-discovery though.
