### ISSUE TITLE
Zone joining works, separating does not

### ISSUE THREAD

**Issue by xsnrg** [jishi/node-sonos-web-controller#37]
Greetings,

I am able to join two players into a group by dragging and dropping them in the left panel, but I cannot separate them by pulling them apart.

**Comment by jishi** [comment]
Fixed zone degrouping in latest commit.

**Comment by xsnrg** [comment]
Thanks for the update.  In the latest commit, when changing the volume, a stack trace is created with the copns not defined.  This was added on line 141.
