### ISSUE TITLE
changed port but socket is still using 8080

### ISSUE THREAD

**Issue by arins** [jishi/node-sonos-web-controller#43]
changed port but socket is still using 8080

**Comment by jishi** [comment]
That shouldn't be possible, since the socket.io is piggybacking on the actual http server that has started. Are you saying that the web interface change port, but the socket.io can no longer connect?

**Comment by jishi** [comment]
Aha, the web interface is trying to connect to port 8080 since someone hardcoded it, sigh...

**Comment by arins** [comment]
exactly

**Comment by GermanBluefox** [comment]
Here
https://github.com/jishi/node-sonos-web-controller/blob/master/static/js/socket.js#L8

**Comment by arins** [comment]
i fixed this in my fork
