### ISSUE TITLE
Ungrouping works, grouping does not

### ISSUE THREAD

**Issue by hexadecagram** [jishi/node-sonos-web-controller#44]
It seems that a recent Sonos update made it so.

**Comment by lfaraone** [comment]
Works for me.
* Controller: version 6.3.2 (build 321131051)
* PLAY:5 version 6.3 (build 321130162a)
* PLAYBAR: version 6.3 (build 321130071)

**Comment by jishi** [comment]
Works on my machine, although it can be improved for systems with many players.
