### ISSUE TITLE
getting the web controller service to start automatically on a pi 

### ISSUE THREAD

**Issue by autofrank** [jishi/node-sonos-web-controller#53]
Hi,
I'm trying to get the web controller to start automatically using your suggestion in issue #330

create the same approach but for the web controller...
/etc/local.d/http-api.start
/flash/apps/runner/start_http_api.sh

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

The web controller files are located at  
/flash/apps/node-sonos-web-controller

I created a web-controller.start file in /etc/local.d/ and persisted it with lbu_commit

```
#!/bin/sh
/flash/apps/runner/start_web_controller.sh &
```

I created a shell file called start_web_controller.sh in /flash/apps/runner/

```
#!/bin/sh
while (true); do
    /usr/bin/node /flash/apps/node-sonos-web-controller/server.js > /flash/logs/web-cont.log
    sleep 10
done
```

but when I restart the pi the web controller doesnt startautomatically
If i go to /flash/apps/node-sonos-web-controller and issue node server.js from putty the web controller starts

Did I miss a step ?

thanks
-f

**Comment by jishi** [comment]
Did you remember to make both files executable?

`chmod a+x /flash/apps/runner/start_web_controller.sh`
`chmod a+x /etc/local.d/web-controller.start`

I also assume that you can run the web-controller manually, to begin with? (installed all dependencies etc)? I'm not 100% sure how the web-controller behaves if started from another directory, you should try starting it manually from the root users home folder just to make sure it works:

```
cd ~
node /flash/apps/node-sonos-web-controller/server.js
```

**Comment by autofrank** [comment]
thanks - I forgot to make the files executable

all working now
-f
