### ISSUE TITLE
Not compatible with latest sonos-discovery 1.2.5 (only 1.1.3)

### ISSUE THREAD

**Issue by GermanBluefox** [jishi/node-sonos-web-controller#56]

**Comment by jishi** [comment]
Could you please expand exactly what doesn't work? My tests doesn't indicate any issues with it.

**Comment by GermanBluefox** [comment]
I will try. First attempts showed that play/pause and volume do not work.
But anyway I will try to find more precise info.

2016-12-18 16:06 GMT+01:00 Jimmy Shimizu <notifications@github.com>:
