### ISSUE TITLE
Play/Pause button stuck  (re-opening from #25 & #26)

### ISSUE THREAD

**Issue by Explorer-OL** [jishi/node-sonos-web-controller#66]
Hi Jishi,

It seems that this issue of songs are continuing to play. Play button sticks without the possibility to get to pause.
Running windows 10 with Chrome version 76.0.3809.100.
Node version 8.11.3
Thx
OL

**Comment by jishi** [comment]
This should work again, verified it on v8, v10 and v12, albeit on MacOS (but shouldn't matter).

**Comment by Explorer-OL** [comment]
Thank you Jishi.

Upon reinstalling the node modules, it fixed indeed in particular, the Play/Pause as well as Now Playing section and current track slider.

Note as info, I wanted to play the Web controller on Android phones. In order to use the list of Favorites, I had to go around the challenge of double tap that zoomed in/out.
I figured that it required only to change Dblclick to Click on the "music favorites" section in the "gui-event.js file". 
With Firefox browser installed it works fine on my phones, Apple's browser works also fine.
 
Thanks to your work, I can now access my Sonos players from another subnet (even from outside like 4G network if I forwarded the ports though of course that as little value to play music while away from home!).

Thanks for taking the time to look at your work again and refreshing it for all of us.
OL

**Comment by jishi** [comment]
There is a mobile view that I started if you visit /m but it lacks the
favorite selection part. Maybe you'd wanna look into adding that of you
have some knowledge about web development. The normal interface is indeed
not mobile friendly, I figured it wouldn't make much sense to have the same
ui for touch devices.
